# Generated by Django 4.0 on 2023-02-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRestaurante', models.CharField(max_length=25)),
                ('identificacionUsuario', models.BigIntegerField()),
                ('menu', models.CharField(max_length=100)),
                ('valorMenu', models.BigIntegerField()),
                ('fechaPago', models.DateTimeField(auto_now=True)),
                ('valorPagado', models.BigIntegerField()),
            ],
        ),
    ]
