# Generated by Django 4.0 on 2023-02-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRestaurante', models.CharField(max_length=25)),
                ('identificacionUsuario', models.BigIntegerField(max_length=10)),
                ('valorMenu', models.BigIntegerField(max_length=7)),
                ('fechaPago', models.DateField(auto_now_add=True)),
                ('valorPagado', models.BigIntegerField(max_length=7)),
            ],
        ),
    ]
