0002_restaurante_delete_person# Generated by Django 4.0 on 2023-02-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRestaurante', models.CharField(max_length=25)),
                ('identificacionUsuario', models.BigIntegerField()),
                ('valorMenu', models.BigIntegerField()),
                ('fechaPago', models.DateField(auto_now_add=True)),
                ('valorPagado', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
