# Generated by Django 4.0 on 2023-02-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_restaurante_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='fechaPago',
            field=models.DateField(auto_now=True),
        ),
    ]
