# Generated by Django 4.0 on 2023-02-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_alter_restaurante_fechapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='fechaPago',
            field=models.DateTimeField(),
        ),
    ]
