# Generated by Django 4.0 on 2023-02-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_alter_restaurante_fechapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='menú',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
