# Generated by Django 4.0 on 2023-02-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_restaurante_menú'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='menú',
            field=models.CharField(max_length=100),
        ),
    ]
