# Generated by Django 4.0 on 2023-02-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_alter_restaurante_menú'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='menú',
            new_name='menu',
        ),
    ]
